// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ziczgndsbttapxiphdzm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InppY3pnbmRzYnR0YXB4aXBoZHptIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgzNDk1NDYsImV4cCI6MjA3MzkyNTU0Nn0.nijCbK4Qa5vbr60cKsd7NqJX-AfVbTKkVlvhwQgvxxQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});